Add headless and gymnasium client
- Adds remote input / output over ZeroMQ.
- Adds a gymnasium client in python/minetester subdirectory, which uses the remote input / output.
- Adds headless rendering support. Build with -DBUILD_HEADLESS=TRUE and run with --headless. Only supported on Linux.
- Somewhat unrelated, but switches the CI to use conda packages for most dependencies.

Co-Authored-By: Gary Mindlin Miguel <garymm@astera.org>

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -43,7 +43,17 @@ jobs:
           source ./util/ci/common.sh
           install_linux_deps g++-7
 
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          python-version: '3.11'
+          mamba-version: "*"
+          channels: conda-forge,nodefaults
+          activate-environment: minetest
+          environment-file: environment.yml
+
       - name: Build
+        # Needed so conda environment is active
+        shell: bash -l {0}
         run: |
           ./util/ci/build.sh
         env:
@@ -64,7 +74,17 @@ jobs:
           source ./util/ci/common.sh
           install_linux_deps g++-12 libluajit-5.1-dev
 
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          python-version: '3.11'
+          mamba-version: "*"
+          channels: conda-forge,nodefaults
+          activate-environment: minetest
+          environment-file: environment.yml
+
       - name: Build
+        # Needed so conda environment is active
+        shell: bash -l {0}
         run: |
           ./util/ci/build.sh
         env:
@@ -85,12 +105,23 @@ jobs:
           source ./util/ci/common.sh
           install_linux_deps clang-7 valgrind
 
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          python-version: '3.11'
+          mamba-version: "*"
+          channels: conda-forge,nodefaults
+          activate-environment: minetest
+          environment-file: environment.yml
+
       - name: Build
+        # Needed so conda environment is active
+        shell: bash -l {0}
         run: |
           ./util/ci/build.sh
         env:
           CC: clang-7
           CXX: clang++-7
+          CMAKE_FLAGS: "-DENABLE_CURSES=FALSE"
 
       - name: Unittest
         run: |
@@ -110,7 +141,17 @@ jobs:
           source ./util/ci/common.sh
           install_linux_deps clang-14 gdb
 
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          python-version: '3.11'
+          mamba-version: "*"
+          channels: conda-forge,nodefaults
+          activate-environment: minetest
+          environment-file: environment.yml
+
       - name: Build
+        # Needed so conda environment is active
+        shell: bash -l {0}
         run: |
           ./util/ci/build.sh
         env:
@@ -125,6 +166,46 @@ jobs:
         run: |
           ./util/test_multiplayer.sh
 
+  pytest:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v3
+      - name: Install deps
+        run: |
+          source ./util/ci/common.sh
+          install_linux_deps clang-14
+
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          python-version: '3.11'
+          mamba-version: "*"
+          channels: conda-forge,nodefaults
+          activate-environment: minetest
+          environment-file: environment.yml
+
+      - name: Build
+        # Needed so conda environment is active
+        shell: bash -l {0}
+        run: |
+          ./util/ci/build.sh
+        env:
+          CC: clang-14
+          CXX: clang++-14
+
+      - name: Run pytest
+        # Needed so conda environment is active
+        shell: bash -l {0}
+        run: |
+          cd python
+          set +o errexit
+          timeout --signal=KILL 5m pytest -v
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "test failed, printing minetest logs"
+            find artifacts/log -type f -name '*.log' -exec cat {} \;
+          fi
+          exit $exit_code
+
   # Build with prometheus-cpp (server-only)
   clang_9_prometheus:
     name: "clang_9 (PROMETHEUS=1)"
@@ -136,28 +217,29 @@ jobs:
           source ./util/ci/common.sh
           install_linux_deps clang-9
 
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          python-version: '3.11'
+          mamba-version: "*"
+          channels: conda-forge,nodefaults
+          activate-environment: minetest
+          environment-file: environment.yml
+
       - name: Build prometheus-cpp
+        shell: bash -l {0}
         run: |
           ./util/ci/build_prometheus_cpp.sh
 
       - name: Build
+        # Needed so conda environment is active
+        shell: bash -l {0}
         run: |
           ./util/ci/build.sh
         env:
           CC: clang-9
           CXX: clang++-9
-          CMAKE_FLAGS: "-DENABLE_PROMETHEUS=1 -DBUILD_CLIENT=0"
+          CMAKE_FLAGS: "-DENABLE_PROMETHEUS=1 -DBUILD_CLIENT=0 -DENABLE_CURSES=FALSE"
 
       - name: Test
         run: |
           ./bin/minetestserver --run-unittests
-
-  docker:
-    name: "Docker image"
-    runs-on: ubuntu-20.04
-    steps:
-      - uses: actions/checkout@v3
-      - name: Build docker image
-        run: |
-          docker build . -t minetest:latest
-          docker run --rm minetest:latest /usr/local/bin/minetestserver --version
